app:
  imageConfig:
    registry: ghcr.io
    repository: codriverlabs/eks-dx-karpenter-support
    tag: latest

clusterIdentity:
  clusterName: ""
  tenantId: ""
  natGatewayEnabled: "false"
  publicSubnetId: ""
  privateSubnetId: ""
  securityGroupId: ""
