app:
  imageConfig:
    registry: ghcr.io
    repository: plasticity-of-cloud/eks-d-xpress-karpenter-support
    tag: latest

clusterIdentity:
  clusterName: ""
  tenantId: ""
  natGatewayEnabled: "false"
  publicSubnetId: ""
  privateSubnetId: ""
  securityGroupId: ""
