quarkus.banner.enabled=false
quarkus.log.level=WARN

# Native build configuration
quarkus.native.additional-build-args=\
  --initialize-at-run-time=software.amazon.awssdk.checksums.internal.ChecksumProvider,\
  -H:+ReportExceptionStackTraces
quarkus.native.resources.includes=application.properties
quarkus.native.output-name-prefix=eks-dx
quarkus.package.jar.type=uber-jar
