quarkus.banner.enabled=false
quarkus.log.level=WARN

# Native build configuration
quarkus.native.additional-build-args=\
  --initialize-at-run-time=io.fabric8.kubernetes.client.impl.KubernetesClientImpl,\
  -H:+ReportExceptionStackTraces
quarkus.native.resources.includes=application.properties
quarkus.package.jar.type=uber-jar
