---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eks-dx-karpenter-support-selfsigned
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-dx-karpenter-support-ca
  namespace: kube-system
spec:
  isCA: true
  commonName: eks-dx-karpenter-support-ca
  secretName: eks-dx-karpenter-support-ca
  issuerRef:
    name: eks-dx-karpenter-support-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eks-dx-karpenter-support-ca
  namespace: kube-system
spec:
  ca:
    secretName: eks-dx-karpenter-support-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-dx-karpenter-support-cert
  namespace: kube-system
spec:
  secretName: eks-dx-karpenter-support-tls
  issuerRef:
    name: eks-dx-karpenter-support-ca
    kind: Issuer
  dnsNames:
    - eks-dx-karpenter-support.kube-system.svc
    - eks-dx-karpenter-support.kube-system.svc.cluster.local
